### PR TITLE
Updated Docs

### PR DESCRIPTION
**Pull request by KaranGRohit**

### CODE REVIEW

**Review by TechnoBlogger14o3 — COMMENTED** [review]
Bro, even if I merge, HactoberFest will put this for 14 Days Review, and if they think its a valid PR then only it will be counted. 
So, my suggestion, write 1-2 programs, add new folder and push it. I'll Merge. Even this one I'm going to merge. Fingers Crossed.

**Comment by keikoro** [comment]
@TechnoBlogger14o3 I don't understand why you're even accepting this. He's already getting his PRs labelled as invalid by other maintainers because they are nonsensical, hopefully DO will pay attention.

**Comment by TechnoBlogger14o3** [comment]
@keikoro Thanks for putting this, I already told him, even if I merge, hacktober team will make it as invalid in its Review Period.

**Comment by keikoro** [comment]
@TechnoBlogger14o3 I think you are misunderstanding how this works. No-one goes and checks if the tens of thousands of PRs that are submitted by people participating are valid. It's done in an automated way, and you approved the PR both by labelling it as accepted and by merging it.

**Comment by TechnoBlogger14o3** [comment]
@keikoro will keep in mind from next time.
Thanks.

**Pull request merged**
